In [1]:
import pandas as pd

data = pd.read_csv("../2021/K2021.csv")
data.head()

,Table Energy Sold by Type of Customers (GWh),Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,2021,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,PLN Operational Unit/ Residential Industrial B...,Residential,Industrial,Business,Social,Gov. Office,Publ. Street,Total,(%)
1,Province,NaN,NaN,NaN,NaN,Building,Lighting,NaN,NaN
2,UIW Aceh,"1,929.59",190.56,515.04,208.23,107.18,123.87,"3,074.47",1.19
3,UIW North Sumatera,"5,998.75","3,082.97","1,672.31",432.68,146.38,415.31,"11,748.40",4.56
4,UIW West Sumatera,"1,781.19",945.24,573.7,169.92,80.45,95.7,"3,646.20",1.42

In [2]:

data.columns = ['Province', 'Residential', 'Industrial', 'Business', 'Social', 'Gov_Office', 'Pub_Street', 'Total', 'Percentage']
data = data.drop(index=[0,1])
data.head()

,Province,Residential,Industrial,Business,Social,Gov_Office,Pub_Street,Total,Percentage
2,UIW Aceh,"1,929.59",190.56,515.04,208.23,107.18,123.87,"3,074.47",1.19
3,UIW North Sumatera,"5,998.75","3,082.97","1,672.31",432.68,146.38,415.31,"11,748.40",4.56
4,UIW West Sumatera,"1,781.19",945.24,573.7,169.92,80.45,95.7,"3,646.20",1.42
5,UIW Riau and Riau Archipelago,"3,431.96","1,633.60","1,408.09",259.18,151.32,137.01,"7,021.16",2.73
6,- Riau,"2,935.09","1,593.61","1,130.68",222.55,112.15,114.24,"6,108.32",2.37

In [3]:
provinsi_valid = [
    "Aceh", "Sumatera Utara", "Sumatera Barat", "Riau", "Kep. Riau", "Jambi", 
    "Sumatera Selatan", "Kep. Bangka Belitung", "Bengkulu", "Lampung", "DKI Jakarta", 
    "Jawa Barat", "Banten", "Jawa Tengah", "DI Yogyakarta", "Jawa Timur", "Kalimantan Barat", 
    "Kalimantan Tengah", "Kalimantan Selatan", "Kalimantan Timur", "Kalimantan Utara", 
    "Sulawesi Utara", "Gorontalo", "Sulawesi Tengah", "Sulawesi Selatan", "Sulawesi Barat", 
    "Sulawesi Tenggara", "Bali", "Nusa Tenggara Barat", "Nusa Tenggara Timur", "Maluku", 
    "Maluku Utara", "Papua Barat", "Papua"
]
def clean_province_name(province_name):
    province_name = province_name.replace('-', '').strip()  
    province_name = province_name.replace("UIW ", "").strip()  
    province_name = province_name.replace("UID", "").strip()  
    province_name = province_name.replace("J a v a", "Indonesia").replace("I n d o n e s i a", "Indonesia")  
    province_name = province_name.replace("North Sumatera", "Sumatera Utara")
    province_name = province_name.replace("South Sumatera", "Sumatera Selatan")
    province_name = province_name.replace("Central Java", "Jawa Tengah")
    province_name = province_name.replace("West Java", "Jawa Barat")
    province_name = province_name.replace("D.I. Yogyakarta", "DI Yogyakarta")
    province_name = province_name.replace("West Kalimantan", "Kalimantan Barat")
    province_name = province_name.replace("East Java", "Jawa Timur")
    province_name = province_name.replace("West Papua", "Papua Barat")
    province_name = province_name.replace("Papua and West Papua", "Papua") 

    province_name = province_name.replace("West Sumatera", "Sumatera Barat")
    province_name = province_name.replace("Riau Archipelago", "Kep. Riau")
    province_name = province_name.replace("Bangka Belitung", "Kep. Bangka Belitung")
    province_name = province_name.replace("South Kalimantan", "Kalimantan Selatan")
    province_name = province_name.replace("Central Kalimantan", "Kalimantan Tengah")
    province_name = province_name.replace("East and North Kalimantan", "Kalimantan Timur")
    province_name = province_name.replace("North Sulawesi", "Sulawesi Utara")
    province_name = province_name.replace("Central Sulawesi", "Sulawesi Tengah")
    province_name = province_name.replace("South Sulawesi", "Sulawesi Selatan")
    province_name = province_name.replace("Southeast Sulawesi", "Sulawesi Tenggara")
    province_name = province_name.replace("West Sulawesi", "Sulawesi Barat")
    province_name = province_name.replace("North Maluku", "Maluku Utara")
    province_name = province_name.replace("West Nusa Tenggara", "Nusa Tenggara Barat")
    province_name = province_name.replace("East Nusa Tenggara", "Nusa Tenggara Timur")
    province_name = province_name.replace("Jakarta Raya", "DKI Jakarta")
    return province_name


data['Province'] = data['Province'].apply(clean_province_name)
data_filtered_new = data[data['Province'].isin(provinsi_valid)]
data_filtered_new.to_csv('data_filtered.csv', index=False)

data_filtered_new.head()

,Province,Residential,Industrial,Business,Social,Gov_Office,Pub_Street,Total,Percentage
2,Aceh,"1,929.59",190.56,515.04,208.23,107.18,123.87,"3,074.47",1.19
3,Sumatera Utara,"5,998.75","3,082.97","1,672.31",432.68,146.38,415.31,"11,748.40",4.56
4,Sumatera Barat,"1,781.19",945.24,573.7,169.92,80.45,95.7,"3,646.20",1.42
6,Riau,"2,935.09","1,593.61","1,130.68",222.55,112.15,114.24,"6,108.32",2.37
7,Kep. Riau,496.87,39.99,277.41,36.63,39.17,22.77,912.84,0.35

In [4]:

numeric_columns = data_filtered_new.select_dtypes(include=['object']).columns  

for column in numeric_columns:
    if column != 'Province':  
        data_filtered_new[column] = data_filtered_new[column].replace({',': ''}, regex=True)  
        data_filtered_new[column] = pd.to_numeric(data_filtered_new[column], errors='coerce') 

data_filtered_new.to_csv('data_no_comma.csv', index=False)
print(data_filtered_new.head())

         Province  Residential  Industrial  Business  Social  Gov_Office  \
2            Aceh      1929.59      190.56    515.04  208.23      107.18
3  Sumatera Utara      5998.75     3082.97   1672.31  432.68      146.38
4  Sumatera Barat      1781.19      945.24    573.70  169.92       80.45
6            Riau      2935.09     1593.61   1130.68  222.55      112.15
7       Kep. Riau       496.87       39.99    277.41   36.63       39.17

   Pub_Street     Total  Percentage
2      123.87   3074.47        1.19
3      415.31  11748.40        4.56
4       95.70   3646.20        1.42
6      114.24   6108.32        2.37
7       22.77    912.84        0.35

C:\Users\Jeff\AppData\Local\Temp\ipykernel_14344\3449822694.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered_new[column] = data_filtered_new[column].replace({',': ''}, regex=True)
C:\Users\Jeff\AppData\Local\Temp\ipykernel_14344\3449822694.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtered_new[column] = pd.to_numeric(data_filtered_new[column], errors='coerce')

In [5]:
kalimantan_timur = data_filtered_new[data_filtered_new['Province'] == 'Kalimantan Timur']
numeric_columns = ['Residential', 'Industrial', 'Business', 'Social', 'Gov_Office', 'Pub_Street', 'Total', 'Percentage']
for column in numeric_columns:
    kalimantan_timur[column] = pd.to_numeric(kalimantan_timur[column], errors='coerce') 

for column in numeric_columns:
    nilai_bagi = kalimantan_timur[column].values[0] / 2
    kalimantan_timur[column] = nilai_bagi 

data_filtered_new = data_filtered_new[data_filtered_new['Province'] != 'Kalimantan Timur']
kalimantan_timur['Province'] = 'Kalimantan Timur' 
data_filtered_new = pd.concat([data_filtered_new, kalimantan_timur], ignore_index=True)
kalimantan_utara = kalimantan_timur.copy() 
kalimantan_utara['Province'] = 'Kalimantan Utara' 
data_filtered_new = pd.concat([data_filtered_new, kalimantan_utara], ignore_index=True)

data_filtered_new = data_filtered_new[data_filtered_new['Province'].isin(provinsi_valid)]
data_filtered_new.to_csv('Hasil_2021.csv', index=False)
print(data_filtered_new.head())

         Province  Residential  Industrial  Business  Social  Gov_Office  \
0            Aceh      1929.59      190.56    515.04  208.23      107.18
1  Sumatera Utara      5998.75     3082.97   1672.31  432.68      146.38
2  Sumatera Barat      1781.19      945.24    573.70  169.92       80.45
3            Riau      2935.09     1593.61   1130.68  222.55      112.15
4       Kep. Riau       496.87       39.99    277.41   36.63       39.17

   Pub_Street     Total  Percentage
0      123.87   3074.47        1.19
1      415.31  11748.40        4.56
2       95.70   3646.20        1.42
3      114.24   6108.32        2.37
4       22.77    912.84        0.35

C:\Users\Jeff\AppData\Local\Temp\ipykernel_14344\724200813.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kalimantan_timur[column] = pd.to_numeric(kalimantan_timur[column], errors='coerce')
C:\Users\Jeff\AppData\Local\Temp\ipykernel_14344\724200813.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kalimantan_timur[column] = nilai_bagi